version: "3"

services:

  eosweb:
    build: .
    ports:
      - 3039:3039
      - 9615:9615
    restart: always
    links:
      - daomongohistory
    environment:
      MONGO_URI: ${NODE_MONGO_URI}
      NODE_URI: ${NODE_URI}
      HISTORY_URI: "http://daomongohistory:3333"


  daomongohistory:
    image: daomongohistory:latest
    ports:
      - 3333:3333
    restart: always
    environment:
      MONGO_URI: ${HISTORY_MONGO_URI}
      NODE_URI: ${NODE_URI}



